# Generated by Django 2.1.15 on 2023-05-14 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.CharField(default=uuid.UUID('2d093539-28c8-4df8-b42a-68f414271ec2'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=255)),
                ('activity_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_id', models.CharField(default=uuid.UUID('43115735-ccd6-4163-87b7-7ab7f3d76cd7'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('case_type', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('case_created_date', models.DateField()),
                ('date_updated', models.DateField()),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('civilian_id', models.CharField(default=uuid.UUID('b69e0345-71e5-48fb-85d1-a7f2271158bf'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'civilians',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('comp_id', models.CharField(default=uuid.UUID('daaa094d-fe1d-460a-9155-584aecaa8612'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('civilian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Civilian')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='Criminals',
            fields=[
                ('criminal_id', models.CharField(default=uuid.UUID('5d1fda67-c667-453d-a387-a1f4783e417c'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('crime_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'criminals',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(default=uuid.UUID('eb881f13-4837-42c4-9087-c88beb16a5b4'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Evidences',
            fields=[
                ('evidence_id', models.CharField(default=uuid.UUID('ad4ddd39-6174-47b7-8f6c-3538b91e61bc'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_added', models.DateField()),
                ('evidence_type', models.CharField(max_length=255)),
                ('evidence_data', models.FileField(upload_to='evidences/')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('FIR_ID', models.CharField(default=uuid.UUID('848a875d-16b8-4b65-9dca-b94baba6bb3e'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'FIR',
            },
        ),
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.CharField(default=uuid.UUID('c572c712-8ddd-4126-a542-c96d3de85c6a'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('logon_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(default='New', max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(default='2023-05-14', null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Department')),
            ],
            options={
                'db_table': 'officers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default=uuid.UUID('f60e047c-4bbe-45dd-8bf5-dde0394195df'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('post_type', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_description', models.TextField()),
                ('post_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.officer')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('privilege_id', models.CharField(default=uuid.UUID('a5003ab9-3367-4158-baab-dbe36777b3e9'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('privilege_name', models.CharField(max_length=255)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.officer')),
            ],
            options={
                'db_table': 'privilege',
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.CharField(default=uuid.UUID('a26909a4-ba54-445a-8a68-63fc2f242e06'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='suspect_photos/')),
            ],
            options={
                'db_table': 'suspect',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(default=uuid.UUID('e08d00fb-d44c-452c-b701-cf1beaa6f41a'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('verdict_id', models.CharField(default=uuid.UUID('0d974e7e-25d9-48e0-815a-08fc214705e2'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('verdict_type', models.CharField(max_length=50)),
                ('verdict_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verdict_description', models.TextField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'verdict',
            },
        ),
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('vict_id', models.CharField(default=uuid.UUID('12fff204-8c55-40a9-8962-955fc3700bfa'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('FIR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.FIR')),
            ],
            options={
                'db_table': 'victims',
            },
        ),
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('warrant_id', models.CharField(default=uuid.UUID('9c8a4cce-1421-417a-81fe-ec4bcf72a781'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('warrant_type', models.CharField(max_length=50)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
                ('suspect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Suspect')),
            ],
            options={
                'db_table': 'warrant',
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('wit_id', models.CharField(default=uuid.UUID('e86e2749-ca2d-452c-975b-bd23ab27d7f8'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('FIR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.FIR')),
            ],
            options={
                'db_table': 'witness',
            },
        ),
        migrations.AddField(
            model_name='suspect',
            name='verdict_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Verdict'),
        ),
        migrations.AddField(
            model_name='officer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='fir',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.officer'),
        ),
        migrations.AddField(
            model_name='cases',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.officer'),
        ),
    ]
