# Generated by Django 2.1.15 on 2023-06-08 15:39

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=255)),
                ('activity_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('caseType', models.CharField(max_length=255, null=True)),
                ('casePriority', models.CharField(max_length=255, null=True)),
                ('caseStatus', models.CharField(default='Open', max_length=255, null=True)),
                ('caseDescription', models.TextField(max_length=255, null=True)),
                ('caseDate', models.DateField(default='2023-06-08', null=True)),
                ('caseNote', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('civilian_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'civilians',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(max_length=255, null=True)),
                ('complaint_date', models.DateField(default='2023-06-08')),
                ('complaint_text', models.TextField(null=True)),
                ('incident_location', models.CharField(max_length=255)),
                ('complaint_status', models.CharField(default='Pending', max_length=255, null=True)),
                ('civilian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Civilian')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('type_of_crime', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'crime',
            },
        ),
        migrations.CreateModel(
            name='Criminals',
            fields=[
                ('criminal_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('crime_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'criminals',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Evidences',
            fields=[
                ('evidence_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date_added', models.DateField(default='2023-06-08')),
                ('evidence_type', models.CharField(default='Image', max_length=255)),
                ('evidence_data', models.FileField(storage=backend.models.CustomStorage(), upload_to='evidences/')),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('FIR_ID', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('summary_of_interview', models.TextField(null=True)),
                ('additional_contacts_witnesses', models.TextField(null=True)),
                ('incident_location_detail', models.TextField(null=True)),
                ('officer_remark', models.TextField(null=True)),
                ('civilian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Civilian')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Evidences')),
            ],
            options={
                'db_table': 'FIR',
            },
        ),
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('logon_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(default='New', max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(default='2023-06-08', null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Department')),
            ],
            options={
                'db_table': 'officers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('post_date', models.DateField(default='2023-06-08', null=True)),
                ('person_name', models.CharField(max_length=100, null=True)),
                ('person_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('person_sex', models.CharField(max_length=100, null=True)),
                ('person_physical_description', models.TextField(null=True)),
                ('person_distinguishing_features', models.TextField(null=True)),
                ('contact_information', models.CharField(max_length=250, null=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.officer')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('privilege_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('privilege_name', models.CharField(max_length=255)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.officer')),
            ],
            options={
                'db_table': 'privilege',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=60)),
                ('report_date', models.DateField(default='2023-06-08')),
                ('report_body', models.TextField()),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('suspectFullName', models.CharField(max_length=100)),
                ('suspectAge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suspectGender', models.CharField(max_length=20)),
                ('suspectAddress', models.TextField()),
                ('suspectPhone', models.CharField(max_length=20)),
                ('suspectRelationship', models.CharField(max_length=255, null=True)),
                ('suspectNotes', models.TextField(null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'suspect',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateField(default='2023-06-08')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('verdict_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('verdict_type', models.CharField(max_length=50)),
                ('verdict_date', models.DateField(default='2023-06-08')),
                ('verdict_description', models.TextField()),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'verdict',
            },
        ),
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('vict_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('victim_name', models.CharField(max_length=100)),
                ('victim_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('victim_gender', models.CharField(max_length=20, null=True)),
                ('victim_address', models.TextField()),
                ('victim_injuries', models.TextField(null=True)),
                ('victim_medicalInfo', models.TextField(null=True)),
                ('victim_phone', models.CharField(max_length=20)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'victims',
            },
        ),
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('warrant_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('warrant_type', models.CharField(max_length=50)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
                ('suspect_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Suspect')),
            ],
            options={
                'db_table': 'warrant',
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('wit_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('witnessFullName', models.CharField(max_length=255)),
                ('witnessAge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('witnessGender', models.CharField(max_length=20, null=True)),
                ('witnessAddress', models.TextField()),
                ('witnessPhone', models.CharField(max_length=20)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases')),
            ],
            options={
                'db_table': 'witness',
            },
        ),
        migrations.AddField(
            model_name='suspect',
            name='verdict_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Verdict'),
        ),
        migrations.AddField(
            model_name='officer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='fir',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.officer'),
        ),
        migrations.AddField(
            model_name='crime',
            name='suspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Suspect'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.officer'),
        ),
    ]
