# Generated by Django 2.1.15 on 2023-06-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='caseDate',
            field=models.DateField(default='2023-06-15', null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_date',
            field=models.DateField(default='2023-06-15'),
        ),
        migrations.AlterField(
            model_name='evidences',
            name='date_added',
            field=models.DateField(default='2023-06-15'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateField(default='2023-06-15', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default='2023-06-15', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='2023-06-15'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateField(default='2023-06-15'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='verdict_date',
            field=models.DateField(default='2023-06-15'),
        ),
    ]
