# Generated by Django 2.1.15 on 2023-05-14 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='log_id',
            field=models.CharField(default=uuid.UUID('b24ab29a-92ab-42cf-80d5-c2d3a38b02b9'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_id',
            field=models.CharField(default=uuid.UUID('c354ebf3-f700-407c-8667-c184f3eb91c2'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='civilian',
            name='civilian_id',
            field=models.CharField(default=uuid.UUID('f010b5ca-376b-4b3a-a3d6-1751a0861270'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='comp_id',
            field=models.CharField(default=uuid.UUID('bf780d10-a320-44c3-8554-5100301baa40'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='criminals',
            name='criminal_id',
            field=models.CharField(default=uuid.UUID('1c4e91e7-97b3-4243-ac47-0596b4582015'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(default=uuid.UUID('6fe8052f-7a6c-45dd-b3a6-3f60ed3c7eb7'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidences',
            name='evidence_id',
            field=models.CharField(default=uuid.UUID('fc48f8b2-abe0-44a9-a50f-b4501692f441'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fir',
            name='FIR_ID',
            field=models.CharField(default=uuid.UUID('5d70538c-47b8-48d4-824e-55c163eebc7d'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officer',
            name='id',
            field=models.CharField(default=uuid.UUID('b4afd94e-cde9-4708-b6d6-8a71d4f6f9e0'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=uuid.UUID('84235254-9b2f-4cf3-8894-38ca23624b95'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='privileges',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.officer'),
        ),
        migrations.AlterField(
            model_name='privileges',
            name='privilege_id',
            field=models.CharField(default=uuid.UUID('91531a8f-023e-4829-8b10-e0e830f60e92'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='suspect_id',
            field=models.CharField(default=uuid.UUID('be049273-3988-4fbb-982c-9b045293c1df'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(default=uuid.UUID('bb73a9d5-bdc3-4a86-9919-c32ae8e89bfa'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='verdict_id',
            field=models.CharField(default=uuid.UUID('13bd3c90-6569-4040-89d4-34c101550b9f'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='victims',
            name='vict_id',
            field=models.CharField(default=uuid.UUID('93bbf600-0281-4b77-8a8e-756866e12a0e'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='warrant_id',
            field=models.CharField(default=uuid.UUID('55711d90-2d88-4b9f-bd05-9ad35c0d5831'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='witness',
            name='wit_id',
            field=models.CharField(default=uuid.UUID('f6b2ddae-3090-4866-85a0-c142ab079f8d'), editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
