# Generated by Django 2.1.15 on 2023-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230615_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='id',
            new_name='officer',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_login_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_login_success',
            field=models.BooleanField(default=False),
        ),
    ]
