# Generated by Django 2.1.15 on 2023-05-14 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230514_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('type_of_crime', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('suspect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Suspect')),
            ],
            options={
                'db_table': 'crime',
            },
        ),
    ]
