# Generated by Django 2.1.15 on 2023-06-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230615_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criminals',
        ),
    ]
