# Generated by Django 2.1.15 on 2023-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='victims',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victims',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='victims',
            name='injuries',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='victims',
            name='medical_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='victims',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='victims',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='witness',
            name='address',
            field=models.TextField(),
        ),
    ]
