# Generated by Django 2.1.15 on 2023-06-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_criminals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='suspect',
        ),
        migrations.DeleteModel(
            name='Crime',
        ),
    ]
