# Generated by Django 2.1.15 on 2023-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230514_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='photo',
        ),
        migrations.AddField(
            model_name='suspect',
            name='suspect_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='suspect_relationship',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
