# Generated by Django 2.1.15 on 2023-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230514_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='case_priority',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='case_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='incident_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateField(default='2023-05-15', null=True),
        ),
    ]
