# Generated by Django 2.1.15 on 2023-05-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20230515_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='id',
            new_name='officer',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='time',
        ),
        migrations.AddField(
            model_name='fir',
            name='additional_contacts',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fir',
            name='evidence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Evidences'),
        ),
        migrations.AddField(
            model_name='fir',
            name='incident_location_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fir',
            name='officer_remark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fir',
            name='summary_of_interview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateField(default='2023-05-16', null=True),
        ),
    ]
