# Generated by Django 2.1.15 on 2023-05-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20230517_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases'),
        ),
        migrations.AddField(
            model_name='victims',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases'),
        ),
        migrations.AddField(
            model_name='witness',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Cases'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_created_date',
            field=models.DateField(default='2023-05-18', null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='case_status',
            field=models.CharField(default='New', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateField(default='2023-05-18', null=True),
        ),
    ]
