# Generated by Django 2.1.15 on 2023-05-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20230518_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='team_id',
        ),
    ]
