# Generated by Django 2.1.15 on 2023-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20230518_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspect',
            old_name='address',
            new_name='suspectAddress',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='age',
            new_name='suspectAge',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='name',
            new_name='suspectFullName',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='gender',
            new_name='suspectGender',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='phone',
            new_name='suspectPhone',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='suspect_relationship',
            new_name='suspectRelationship',
        ),
        migrations.AddField(
            model_name='suspect',
            name='suspectNotes',
            field=models.TextField(null=True),
        ),
    ]
