# Generated by Django 2.1.15 on 2023-05-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20230518_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='witness',
            old_name='address',
            new_name='witnessAddress',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='age',
            new_name='witnessAge',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='name',
            new_name='witnessFullName',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='gender',
            new_name='witnessGender',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='phone',
            new_name='witnessPhone',
        ),
    ]
