# Generated by Django 2.1.15 on 2023-05-21 07:21

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_cases_incidentdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='caseDate',
            field=models.DateField(default='2023-05-21', null=True),
        ),
        migrations.AlterField(
            model_name='evidences',
            name='date_added',
            field=models.DateField(default='2023-05-21'),
        ),
        migrations.AlterField(
            model_name='evidences',
            name='evidence_data',
            field=models.FileField(storage=backend.models.CustomStorage(), upload_to='media/evidences/'),
        ),
        migrations.AlterField(
            model_name='evidences',
            name='evidence_type',
            field=models.CharField(default='Image', max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateField(default='2023-05-21', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateField(default='2023-05-21'),
        ),
    ]
