# Generated by Django 2.1.15 on 2023-05-21 14:07

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20230521_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='description',
            new_name='complaint_body',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='date',
            new_name='complaint_date',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='comp_id',
            new_name='complaint_id',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='location',
            new_name='complaint_location',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='status',
            new_name='complaint_status',
        ),
        migrations.AlterField(
            model_name='evidences',
            name='evidence_data',
            field=models.FileField(storage=backend.models.CustomStorage(), upload_to='evidences/'),
        ),
    ]
