# Generated by Django 2.1.15 on 2023-05-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20230521_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_date',
            field=models.DateField(default='2023-05-21'),
        ),
    ]
