# Generated by Django 2.1.15 on 2023-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20230521_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
