# Generated by Django 2.1.15 on 2023-05-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20230521_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='civilian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Civilian'),
        ),
    ]
