# Generated by Django 2.1.15 on 2023-05-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_fir_civilian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='civilian_id',
            new_name='civilian',
        ),
    ]
