# Generated by Django 2.1.15 on 2023-05-22 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20230521_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=60)),
                ('report_date', models.DateField(default='2023-05-22')),
                ('report_body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cases',
            name='caseDate',
            field=models.DateField(default='2023-05-22', null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_date',
            field=models.DateField(default='2023-05-22'),
        ),
        migrations.AlterField(
            model_name='evidences',
            name='date_added',
            field=models.DateField(default='2023-05-22'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateField(default='2023-05-22', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateField(default='2023-05-22'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='verdict_date',
            field=models.DateField(default='2023-05-22'),
        ),
        migrations.AddField(
            model_name='report',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.officer'),
        ),
    ]
