# Generated by Django 2.1.15 on 2023-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20230522_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='additional_contacts',
            new_name='additional_contacts_witnesses',
        ),
        migrations.AlterField(
            model_name='cases',
            name='caseDate',
            field=models.DateField(default='2023-05-23', null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_date',
            field=models.DateField(default='2023-05-23'),
        ),
        migrations.AlterField(
            model_name='evidences',
            name='date_added',
            field=models.DateField(default='2023-05-23'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_at',
            field=models.DateField(default='2023-05-23', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='2023-05-23'),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateField(default='2023-05-23'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='verdict_date',
            field=models.DateField(default='2023-05-23'),
        ),
    ]
