# Generated by Django 2.1.15 on 2023-05-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20230524_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='officer',
        ),
    ]
